### ISSUE TITLE
Issue Exposing Classes: Undefined Symbol _Libcpptcl_module_five_Init

### ISSUE THREAD

**Issue by AndruePeters** [flightaware/cpptcl#19]
Unable to load any examples except forcpptcl_example_functions.cc

`$make && make install && make examples`
` $cd build/examples`
` $tclsh`
 `%load ./liblibcpptcl_module_five.so`
`cannot find symbol "Libcpptcl_module_five_Init": ./liblibcpptcl_module_five.so: undefined symbol: _Libcpptcl_module_five_Init
`
This is using CMake 3.16 and clang9 and tcl8.6.
I'm still investigating, but wanted to go ahead and put this here. I can successfully load `libcpptcl_example_functions.so `, but nothing else from examples.

[EDIT] This was actually an issue with naming of the resulting shared object.

**Comment by snoe925** [comment]
Please pull v2.2.4.
There was an extra lib in the names in the CMakeLists.txt files.
There were also two files where the name in the .cc file did not correctly match the file name.
But after these fixes.
```
# tclsh
tcl> load ./build/examples/libcpptcl_module_five.so
tcl> set p [makePerson Jane]
p0x55734a997330
tcl> $p getName
Jane
```
If you still have problems please comment here, and I will reopen the issue.

**Comment by AndruePeters** [comment]
I was going to comment that actually. I fixed it myself.

Could you update the documentation for what extending TCL?
The module name must start with a capital letter and the resulting shared object file must have the same name as the module.

```CPPTCL_MODULE(Mymodule, i)  ```, must have a shared object named Mymodule.x. Extension didn't seem to matter. ```CPPTCL_MODULE(mymodule, i)  ``` will never be able to link correctly, because whatever mechanism that loads the file capitalizes the first character. I couldn't find any documentation that specified how naming should work. It took me a while to track down.

**Comment by snoe925** [comment]
I will add a new section to the cpptcl docs on naming extensions.  The uppercase / lowercase logic is documented in the load command man page.  It's not very obvious.

https://www.tcl-lang.org/man/tcl/TclCmd/load.htm
https://github.com/tcltk/tcl/blame/5ab3176cebb7cdd8ea0498d07d28d6d5c1d95e21/generic/tclLoad.c#L368
