### ISSUE TITLE
modules/example_functions forces use of clang++

### ISSUE THREAD

**Issue by mutability** [flightaware/cpptcl#7]
Building on ubuntu 16.04.4 with clang-5.0 installed
(notably, all the installed clang++ binaries are versioned, there is no plain `clang++`)

some of the subdirs ignore CXX

```
$ make CXX=clang++-5.0 CC=clang-5.0 VERBOSE=1
[...]
(cd modules/example_functions; mkdir -p build)
(cd modules/example_functions/build; cmake -DCPPTCL_SOURCE_DIR=$PWD/../../../ ..)
Re-run cmake no build system arguments
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_CXX_COMPILER:

    clang++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by snoe925** [comment]
I think this might work if you set CXX and CC in the shell env instead of make variables.  Can you try that? ```CXX=clang++-5.0 CC=clang-5.0 make ...```

**Comment by snoe925** [comment]
The CXX passing to make will not work.  A full example of Linux + Clang-5.0 is here.
https://github.com/flightaware/cpptcl/blob/master/docker/Dockerfile.xenial-clang-5
